language: python
python:
  - "3.9.7"
jobs:
  include:
    - name: "Run pytest tests"
      if: type = pull_request
      install:
        - pip install -r requirements.txt
      script:
        - pytest